config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#main'
  get 'top/main', to: 'top#main'
  get 'top/logout', to: 'top#logout'
  get 'top/error', to: 'top#error'
  post 'top/login', to: 'top#login'
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.authenticate?(user_pass, request_pass)
    if BCrypt::Password.new(user_pass) == request_pass
      return true
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:uid].nil?
      render "main"
    else
      render "login"
    end
  end

  def login
    user = User.find_by(uid: user_params[:uid])
    return redirect_to top_error_path if user.nil?

    if User.authenticate?(user.pass, user_params[:pass])
      session[:uid] ||= user.uid
      redirect_to top_main_path
    else
      redirect_to top_error_path
    end
  end

  def logout
    session.delete(:uid)
    redirect_to root_path
  end

  def error
  end

  private

  def user_params
    params.permit(:uid, :pass)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.pass = BCrypt::Password.create(user_params[:pass])
    if @user.save
      redirect_to root_path
    else
      render new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:uid, :pass)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swdev05</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>ログイン失敗</h1>
<%= link_to 'もどる', root_path %>

app/views/top/login.html.erb
<h1>ログイン成功</h1>
Welcome "<%= session[:uid] %>" !!<br>
<br>
<%= link_to 'ログアウト', top_logout_path %>

app/views/top/main.html.erb
<h1>Login</h1>
<%= form_with url: 'top/login' do |form| %>
  <%= form.label :uid, 'User ID' %>
  <%= form.text_field :uid %>
  <br>
  <%= form.label :pass, 'Password' %>
  <%= form.text_field :pass %>
  <br>
  <%= form.submit 'Submit' %>
<% end %>
<br>
<%= link_to 'Create User', new_user_path %>

app/views/users/new.html.erb
<h1>Add new user</h1>

<%= form_with model: @user, url: {action: :create} do |f| %>
  <%= f.label :uid, 'User ID' %>
  <%= f.text_field :uid %>
  <br>
  <%= f.label :pass, 'Password' %>
  <%= f.text_field :pass %>
  <br>
  <%= f.submit 'Submit' %>
<% end %>